version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html 
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306

volumes:
  mysql-data:
